
services:
  postgres:
    image: 'postgres:15'
    container_name: 'triptrail-postgres'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=triptraildb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

